# -*- coding: utf-8 -*-
"""
接口全局变量
"""

# 接口全局配置
API_ENVIRONMENT_DEBUG = 'debug'
API_ENVIRONMENT_RELEASE = 'release'

# 接口响应时间list，单位毫秒
STRESS_LIST = []

# 接口执行结果list
RESULT_LIST = []

# 设备类型值category_type
AD_SCREEN = 'AD_SCREEN'
IPC = 'IPC'
LAMP = 'LAMP'
WEATHER_STATION = 'WEATHER_STATION'
SYNTHESIS_DEVICE_BOX = 'SYNTHESIS_DEVICE_BOX'
LANDSCAPE_LAMP = 'LANDSCAPE_LAMP'
LAMP_POLE = 'LAMP_POLE'
CAMERA = 'CAMERA'
BROADCAST = 'BROADCAST'
MANHOLE_COVER = 'MANHOLE_COVER'
SMOKE_DETECTOR = 'SMOKE_DETECTOR'
PRESS_TO_ALARM = 'PRESS_TO_ALARM'

# 设备类型值category_id
AD_SCREEN_ID = 1
IPC_ID = 61
LAMP_ID = 71
WEATHER_STATION_ID = 101
SYNTHESIS_DEVICE_BOX_ID = 131
LANDSCAPE_LAMP_ID = 141
LAMP_POLE_ID = 1000
CAMERA_ID = 11
BROADCAST_ID = 21
MANHOLE_COVER_ID = 31
SMOKE_DETECTOR_ID = 41
PRESS_TO_ALARM_ID = 51

